# Generated by Django 5.0.1 on 2024-01-14 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("firstname", models.CharField(max_length=15)),
                ("lastname", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=15)),
                ("address", models.CharField(blank=True, max_length=100)),
                ("phoneNumber", models.CharField(max_length=10)),
                ("linkedin", models.CharField(blank=True, max_length=50)),
                ("facebook", models.CharField(blank=True, max_length=50)),
                ("twitter", models.CharField(blank=True, max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
